# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_cerveja_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerveja',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 11, 20, 19, 15, 236371, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
