# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20160611_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='CNPJ',
            field=models.CharField(max_length=40),
        ),
    ]
