# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20160612_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacao',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pacote'),
        ),
    ]
