# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20160612_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacao',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
