# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20160612_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinacao',
            name='cervejas',
        ),
        migrations.RemoveField(
            model_name='combinacao',
            name='pacote',
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.DeleteModel(
            name='Combinacao',
        ),
    ]
