# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20160612_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.NullBooleanField()),
                ('cervejas', models.ManyToManyField(to='webapp.Cerveja')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pacote')),
            ],
        ),
    ]
